version: "3"

services:
  db:
    image: postgres
    container_name: gym-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5431:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build: .
    command: uvicorn main:api --host 0.0.0.0 --port 8000 --reload --reload-delay 1
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DB_DATASOURCE}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    networks:
      - mynetwork

  frontend:
    build: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - app
    environment:
      REACT_APP_API_URL: http://app:8000/api
    stdin_open: true
    tty: true
    networks:
      - mynetwork
    volumes:
      - .:/app/frontend

volumes:
  db-data:
    driver: local

networks:
  mynetwork:
    driver: bridge
