"""empty message

Revision ID: 5a141625ccea
Revises: b6eccff9e673
Create Date: 2023-03-11 23:17:49.843408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a141625ccea'
down_revision = 'b6eccff9e673'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('cadence', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'cadence')
    # ### end Alembic commands ###
