"""empty message

Revision ID: b6eccff9e673
Revises: 42dd7afac79f
Create Date: 2023-03-11 22:59:22.070020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6eccff9e673'
down_revision = '42dd7afac79f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exercise_uuid_exercise_type_fkey', 'exercise', type_='foreignkey')
    op.create_foreign_key(None, 'exercise', 'exercise_type', ['uuid_exercise_type'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.create_foreign_key('exercise_uuid_exercise_type_fkey', 'exercise', 'exercise', ['uuid_exercise_type'], ['uuid'])
    # ### end Alembic commands ###
